<?php
/*------------------------------------------------------------------------

# Music Addon

# ------------------------------------------------------------------------

# Author:    DuongTVTemPlaza

# Copyright: Copyright (C) 2016 tzportfolio.com. All Rights Reserved.

# @License - http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL

# Website: http://www.tzportfolio.com

# Technical Support:  Forum - http://tzportfolio.com/forum

# Family website: http://www.templaza.com

-------------------------------------------------------------------------*/

// No direct access
defined('_JEXEC') or die;

class PlgTZ_Portfolio_PlusContentVideoModelArticle extends TZ_Portfolio_PlusPluginModelItem
{
    public function getVideoItems(){
        if($model  = JModelLegacy::getInstance('Video','PlgTZ_Portfolio_PlusContentModel',
            array('ignore_request' => true))) {

            $params = $this -> getState('params');
            $model->setState('params', $params);
            $model->setState('filter.content_id', $this->article->id);

            return $model -> getItems();
        }
        return false;
    }
//    public function getItem($pk = null)
//    {
//        $item   = parent::getItem($pk); // TODO: Change the autogenerated stub
////        if(!$item){
////            if($model  = JModelLegacy::getInstance('Music','PlgTZ_Portfolio_PlusContentModel',
////                array('ignore_request' => true))) {
////
////                $params = $this -> getState('params');
////                $model->setState('params', $params);
////                $model->setState('filter.contentid', $this->article->id);
//////                $model->setState('list.music_order', $params -> get('music_order', 'rdate'));
////
////                $item   = $model -> getItems();
////            }
////        }
//        return $item;
//    }
}